'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { ContinualHarnessStore } = require('../lib/continual-harness');
const { policyId } = require('../lib/behavior-policy');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'z-harness-delete-'));
process.env.Z_HARNESS_GLOBAL_STATE_PATH = path.join(root, 'global.json');
process.env.Z_HARNESS_TEST_EXPORTS = '1';
delete process.env.Z_HARNESS_CONTEXT_DIR;
const { deleteEntry } = require('../lib/z-harness-mcp');
test.after(() => fs.rmSync(root, { recursive: true, force: true }));

test('deletion survives recovery, stale review and reload; explicit rollback restores it', async () => {
  const store = new ContinualHarnessStore({ globalPath: process.env.Z_HARNESS_GLOBAL_STATE_PATH });
  const content = '以后搜索优先使用 AnySearch 工具。';
  const id = `prompt-${policyId(content).replace(/^user-policy-/, '')}`;
  const failed = await store.apply({ trigger: `Agent-requested refinement: ${content}`, edits: [] }, { source: 'agent_refine' });
  await store.recordOutcome(failed.refinement.id, { status: 'rejected' });
  await store.recoverRejectedAgentRefinements();
  assert.equal(store.get('prompt', id).metadata.status, 'active');
  const workspace = path.join(root, 'workspace');
  await store.apply({ edits: [{ action: 'create', kind: 'prompt', id, title: 'Workspace rule', content, scope: 'workspace' }] }, { scope: 'workspace', workspace });
  const context = { workspace, runId: 'delete-run' };
  await assert.rejects(deleteEntry(context, { kind: 'prompt', id }), /explicit scope/);
  const result = await deleteEntry(context, { kind: 'prompt', id, scope: 'global' });
  assert.equal(result.ok, true);
  assert.equal(store.evolutionContext({ query: content }).entries.length, 0);
  assert.equal(store.get('prompt', id, { scope: 'workspace', workspace }).metadata.status, 'active');
  assert.deepEqual(await store.recoverRejectedAgentRefinements(), []);
  const retry = await store.apply({ edits: [{ action: 'update', kind: 'prompt', id, content, metadata: { status: 'active' } }] });
  assert.equal(retry.refinement.appliedEdits[0].applied, false);
  assert.equal((await deleteEntry(context, { kind: 'prompt', id, scope: 'global' })).unchanged, true);
  assert.equal(new ContinualHarnessStore({ globalPath: store.globalPath }).get('prompt', id).metadata.status, 'deleted');
  await store.rollback(result.refinementId);
  assert.equal(store.get('prompt', id).metadata.status, 'active');
});
